// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_demo/test/pages/movie_details/movie_details_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_demo/app/config/app_config.dart' as _i2;
import 'package:flutter_demo/domain/utils/date_time_reader.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfig extends _i1.Mock implements _i2.AppConfig {
  MockAppConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String param(String? paramName) =>
      (super.noSuchMethod(
            Invocation.method(#param, [paramName]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#param, [paramName]),
            ),
          )
          as String);
}

/// A class which mocks [DateTimeReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTimeReader extends _i1.Mock implements _i4.DateTimeReader {
  MockDateTimeReader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime now() =>
      (super.noSuchMethod(
            Invocation.method(#now, []),
            returnValue: _FakeDateTime_0(this, Invocation.method(#now, [])),
          )
          as DateTime);
}
