# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - analyze
  - test

#analyze:
#  image: cirrusci/flutter:3.19.0
#  stage: analyze
#  script:
#    - flutter pub get
#    - flutter analyze

test:
  image: cirrusci/flutter:latest  # base image, even if old, it gives you dart+flutter tools
  stage: test
  before_script:
    - echo "Downloading Flutter 3.29.0"
    - curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.29.0-stable.tar.xz
    - tar xf flutter_linux_3.29.0-stable.tar.xz
    - export PATH="$PWD/flutter/bin:$PATH"
    - flutter --version
  script:
    - flutter pub get
    - flutter test
