// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_demo/test/features/movie_list/movie_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i6;
import 'package:flutter_demo/components/message_dialog.dart' as _i7;
import 'package:flutter_demo/features/movie_details/model/movie.dart' as _i5;
import 'package:flutter_demo/features/movie_list/navigation/movie_list_navigator.dart'
    as _i8;
import 'package:flutter_demo/navigation/app_navigator.dart' as _i2;
import 'package:flutter_demo/navigation/nav_commands_common.dart' as _i9;
import 'package:flutter_demo/repositories/data_movies_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppNavigator_0 extends _i1.SmartFake implements _i2.AppNavigator {
  _FakeAppNavigator_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRepository extends _i1.Mock implements _i3.MoviesRepository {
  MockMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Movie>> getSearchedMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchedMovies, [query]),
            returnValue: _i4.Future<List<_i5.Movie>>.value(<_i5.Movie>[]),
          )
          as _i4.Future<List<_i5.Movie>>);

  @override
  _i4.Future<_i5.Movie?> getMovie(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#getMovie, [movieId]),
            returnValue: _i4.Future<_i5.Movie?>.value(),
          )
          as _i4.Future<_i5.Movie?>);
}

/// A class which mocks [AppNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppNavigator extends _i1.Mock implements _i2.AppNavigator {
  MockAppNavigator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void showProgress(_i6.BuildContext? context) => super.noSuchMethod(
    Invocation.method(#showProgress, [context]),
    returnValueForMissingStub: null,
  );

  @override
  void popProgress(_i6.BuildContext? context) => super.noSuchMethod(
    Invocation.method(#popProgress, [context]),
    returnValueForMissingStub: null,
  );

  @override
  void dialogMessage(_i6.BuildContext? context, _i7.DialogParams? params) =>
      super.noSuchMethod(
        Invocation.method(#dialogMessage, [context, params]),
        returnValueForMissingStub: null,
      );

  @override
  void dialogError(_i6.BuildContext? context, Exception? e) =>
      super.noSuchMethod(
        Invocation.method(#dialogError, [context, e]),
        returnValueForMissingStub: null,
      );

  @override
  void twoButtons(_i6.BuildContext? context) => super.noSuchMethod(
    Invocation.method(#twoButtons, [context]),
    returnValueForMissingStub: null,
  );

  @override
  void movieList(_i6.BuildContext? context) => super.noSuchMethod(
    Invocation.method(#movieList, [context]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MovieListNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieListNavigator extends _i1.Mock
    implements _i8.MovieListNavigator {
  MockMovieListNavigator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppNavigator get appNavigator =>
      (super.noSuchMethod(
            Invocation.getter(#appNavigator),
            returnValue: _FakeAppNavigator_0(
              this,
              Invocation.getter(#appNavigator),
            ),
          )
          as _i2.AppNavigator);

  @override
  void onNullCommand(_i6.BuildContext? context) => super.noSuchMethod(
    Invocation.method(#onNullCommand, [context]),
    returnValueForMissingStub: null,
  );

  @override
  void navigate(
    _i6.BuildContext? context,
    _i9.NavigationCommand<dynamic>? navCommand,
  ) => super.noSuchMethod(
    Invocation.method(#navigate, [context, navCommand]),
    returnValueForMissingStub: null,
  );

  @override
  void go(
    _i6.BuildContext? context,
    _i9.NavigationCommand<dynamic>? navCommand,
  ) => super.noSuchMethod(
    Invocation.method(#go, [context, navCommand]),
    returnValueForMissingStub: null,
  );
}
